# CPSC 375-01
mean(iris[iris$Petal.Length > 3, "Sepal.Length"])
mean(iris[iris$Sepal.Width > 3, "Sepal.Length"])
library(tidyverse)
?mpg
View(mpg)
filter(mpg, cty > 27)
filter(mpg, cty > 27, hwy > 40)
filter(mpg, manufacturer == "honda")
filter(mpg, manufacturer == "honda", manufacturer == "toyota")
filter(mpg, manufacturer == "honda" | manufacturer == "toyota")
filter(mpg, manufacturer %in% c("honda","toyota"))
select(mpg, manufacturer)
select(mpg, manufacturer, model)
select(mpg, 1, 2)
select(mpg, 1:4)
select(filter(mpg, cty > 25), manufacturer, model)
mpg %>% filter(cty > 25) %>% select(manufacturer, model)
mpg %>%
filter(cty > 25) %>%
select(manufacturer, model)

iris %>% filter(Petal.Length > 3, Petal.Width > 1) %>% select(c(Sepal.Length, Sepal.Width))
select(filter(iris, Petal.Length > 3.0, Petal.Width > 1.0), Sepal.Length, Petal.Length)
iris %>% filter(Petal.Length > 3, Petal.Width > 1) %>% select(Sepal.Length, Sepal.Width)
iris %>% filter(Petal.Length > 3, Petal.Width > 1) %>% select(3, 4)
colnames(iris)
iris %>% filter(Petal.Length > 3, Petal.Width > 1) %>% select(1,2)
mpg %>% arrange(cty)
mpg %>% arrange(desc(cty))

# CPSC 375-02
iris[iris$Petal.Length > 3.0,]
iris[iris$Petal.Length > 3.0,"Sepal.Length"]
mean(iris[iris$Petal.Length > 3.0,"Sepal.Length"])
library(tidyverse)
help(mpg)
filter(mpg, cty > 27)
filter(mpg, cty > 27, hwy > 40)
filter(mpg, manufacturer=="honda", manufacturer=="toyota")
filter(mpg, manufacturer=="honda" | manufacturer=="toyota")
filter(mpg, manufacturer %in% c("honda","toyota"))
select(mpg, manufacturer)
select(mpg, manufacturer, model)
mpg[,"manufacturer"]
select(mpg, 1, 2)
select(mpg, 1:4)
select(mpg, starts_with("m"))
select(filter(mpg, cty > 25), manufacturer, model)
mpg %>% filter(cty > 25) %>% select(manufacturer, model)
select(filter(iris, Petal.Length > 3.0, Petal.Width > 1.0),1,2)
iris %>% filter(Petal.Length>3.0, Petal.Width>1.0) %>% select(Sepal.Length, Sepal.Width)
mpg %>% arrange(cty)
mpg %>% arrange(desc(cty))
mpg %>% arrange(-cty)
mpg %>% arrange(-cty, -hwy)
mpg %>% arrange(manufacturer)
mpg %>% arrange(-manufacturer)
mpg %>% arrange(-cty)
mpg %>% arrange(desc(manufacturer))
