library(tidyverse)
mpg %>% arrange(cty,manufacturer)
mpg %>% select(manufacturer, cty) %>% arrange(cty)
mpg %>% select(manufacturer, cty, hwy) %>% arrange(cty,manufacturer)
mpg %>% arrange(+cty) %>% select(manufacturer, cty, hwy)
mpg %>% arrange(cty, hwy) %>% select(manufacturer, cty, hwy)
mpg %>% select(manufacturer, cty, hwy) %>% arrange(-cty)
mpg %>% select(manufacturer, cty, hwy) %>% arrange(desc(cty))
mpg %>% filter(manufacturer=="honda", cty > 25) %>% select(manufacturer, cty, hwy) %>% arrange(-cty)
mpg %>% arrange(desc(cty)) %>% select(manufacturer, cty, hwy) %>% filter(manufacturer == "honda")
mpg %>% filter(manufacturer == 'honda') %>% filter(cty > 25) %>% select(manufacturer,cty, hwy) %>% arrange(desc(cty))
mpg %>% filter(manufacturer == 'honda') %>% filter(cty > 25) %>% select(manufacturer) %>% arrange(desc(cty))
mpg %>% filter(manufacturer=="honda", cty > 25) %>% select(manufacturer)
mpg %>% filter(manufacturer == 'honda') %>% filter(cty > 25) %>% select(manufacturer) %>% arrange(desc(cty)) # <-- error
mpg %>% filter(manufacturer == 'honda') %>% filter(cty > 25)  %>% arrange(desc(cty))%>% select(manufacturer) # <-- correct
mpg %>% filter(manufacturer=="honda", cty > 25) %>% select(manufacturer) %>% view()
mpg %>% view()
(18+29)/2
mpg %>% mutate((cty+hwy)/2) %>% view()
mpg %>% mutate(mileage=(cty+hwy)/2) %>% view()
mpg %>% view()
mpg %>% summarise(mean(hwy))
mean(hwy)
mean(mpg$hwy)
